### ISSUE TITLE
Total license count is incorrect.

### ISSUE THREAD

**Issue by vishalverma1175** [junecastillote/LazyExchangeAdmin.SkuMon#1]
Hi June,

I appreciate your contributions to the scripts. However, since April 2nd, I've noticed an issue with the total license count. For instance, we have 25,000 E5 licenses, it only shows 11,000. 
Would you please verify if any modification happened.

Thanks,

**Comment by junecastillote** [comment]
> Hi June,
> 
> I appreciate your contributions to the scripts. However, since April 2nd, I've noticed an issue with the total license count. For instance, we have 25,000 E5 licenses, it only shows 11,000. Would you please verify if any modification happened.
> 
> Thanks,

Hi,

Sorry but I haven't made any changes to this code. In fact, I am no longer maintaining this because I have created a new module for the same purpose that uses the Microsoft Graph API PowerShell SDK.

Here's the new repo if you're interested.

https://github.com/junecastillote/PsSkuMon365
